use std::{env, fs, path::PathBuf};

fn main() {
    let input = "country-codes.md";
    let contents =
        fs::read_to_string(input).unwrap_or_else(|e| panic!("failed to read {input}: {e}"));

    println!("cargo:rerun-if-changed={input}");

    let entries = parse_country_table(&contents);

    if entries.is_empty() {
        panic!("no PayPal country codes found in {input}");
    }

    let generated = generate_rust(&entries);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let output = out_dir.join("paypal_country_code.rs");

    fs::write(&output, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", output.display()));
}

fn parse_country_table(contents: &str) -> Vec<(&str, &str)> {
    contents
        .lines()
        .skip_while(|line| !line.trim_start().starts_with("| Country or region"))
        .skip(2) // header + separator
        .take_while(|line| line.trim_start().starts_with('|'))
        .filter_map(|line| {
            let columns: Vec<_> = line
                .trim()
                .trim_matches('|')
                .split('|')
                .map(str::trim)
                .collect();

            if columns.len() != 2 {
                return None;
            }

            let name = columns[0];
            let code = columns[1].trim_matches('`');

            if name.is_empty() || code.is_empty() {
                None
            } else {
                Some((name, code))
            }
        })
        .collect()
}

fn generate_rust(entries: &[(&str, &str)]) -> String {
    let mut output = String::new();

    output.push_str(
        r#"// @generated by build.rs -- DO NOT EDIT

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PaypalCountryCode {"#,
    );

    for (name, code) in entries {
        output.push_str(&format!(
            r#"
    /// {name}
    {code},"#
        ));
    }

    output.push_str(
        r#"
}

impl PaypalCountryCode {
    pub fn name(&self) -> &'static str {
        match self {"#,
    );

    for (name, code) in entries {
        output.push_str(&format!(
            r#"
            Self::{code} => "{name}","#,
        ));
    }

    output.push_str(
        r#"
        }
    }

    pub fn from_name(s: &str) -> Option<Self> {
        match s {"#,
    );

    for (name, code) in entries {
        output.push_str(&format!(
            r#"
            "{name}" => Some(Self::{code}),"#,
        ));
    }

    output.push_str(
        r#"
            _ => None,
        }
    }
}

impl std::str::FromStr for PaypalCountryCode {
    type Err = CountryParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {"#,
    );

    for (_, code) in entries {
        output.push_str(&format!(
            r#"
            {code:?} => Ok(Self::{code}),"#
        ));
    }

    output.push_str(
        r#"
            _ => Err(CountryParseError::InvalidCountryCode(s.to_string())),
        }
    }
}

impl std::fmt::Display for PaypalCountryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {"#,
    );

    for (_, code) in entries {
        output.push_str(&format!(
            r#"
            Self::{code} => {code:?},"#
        ));
    }

    output.push_str(
        r#"
        })
    }
}
"#,
    );

    output
}
